export enum RoutesPath {
  USER_HOME_PAGE = '/',
  LOGIN_PAGE = '/login',
  RESET_PAGE = '/reset',
  RESET_PASSWORD_PAGE = '/reset-password/:token',
  ADMIN_HOME_PAGE = '/admin/companies',
  ADMIN_CREATE_COMPANY_PAGE = '/admin/companies/create',
  ADMIN_UPDATE_COMPANY_PAGE = '/admin/companies/update/:id',
  ADMIN_COMPANY_DETAILS_PAGE = '/admin/companies/:id',
  ADMIN_CREATE_CONTACT_PERSON_PAGE = '/admin/companies/:id/contactpersons/create',
  ADMIN_UPDATE_CONTACT_PERSON_PAGE = '/admin/companies/:companyId/contactpersons/update/:id',
  ADMIN_CREATE_USER_PAGE = '/admin/companies/:companyId/users/create',
  ADMIN_UPDATE_USER_PAGE = '/admin/companies/:companyId/users/update/:id',
  ADMIN_ONBOARDING_PAGE = '/admin/companies/:companyId/onboarding',
  ADMIN_CREATE_PRODUCTFEED_PAGE = '/admin/companies/:companyId/productfeeds/create',
  ADMIN_UPDATE_PRODUCTFEED_PAGE = '/admin/companies/:companyId/productfeeds/update/:id',
  ADMIN_DOCUMENTATION_PAGE = '/admin/documentation',
  ADMIN_ROBOT_PAGE = 'admin/robots',
  NOT_FOUND_PAGE = '/not-found',
  UNAUTHORIZED_PAGE = '/unauthorized',
}
